from distutils.core import setup

setup(
    name='WebScrapingPDF',
    version='1.0',
    packages=['app', 'app.auth', 'app.admin', 'app.database', 'app.scheduler', 'app.soup', 'app.static',
              'app.static.css', 'app.static.img', 'app.static.js', 'app.templates', 'app.templates.admin',
              'app.templates.auth'],
    include_package_data=True,
    author='Neueda',
    description="This website will scrape files's off other web pages and display them to anyone who uses the web page",
    entry_points={"run"},
    install_requires=["alembic==0.8.10",
                      "APScheduler==3.3.1",
                      "beautifulsoup4==4.5.3",
                      "blinker==1.4",
                      "bs4==0.0.1",
                      "click==6.7",
                      "decorator==4.0.11",
                      "Flask==0.12",
                      "Flask-Admin==1.4.2",
                      "Flask-APScheduler==1.6.0",
                      "flask-bootstrap-forms==0.4",
                      "Flask-Login==0.3.2",
                      "Flask-Mail==0.9.1",
                      "Flask-Migrate==2.0.3",
                      "Flask-Principal==0.4.0",
                      "Flask-Script==2.0.5",
                      "Flask-Security==1.7.5",
                      "Flask-SQLAlchemy==2.1",
                      "Flask-WTF==0.14.2",
                      "itsdangerous==0.24",
                      "Jinja2==2.9.5",
                      "Mako==1.0.6",
                      "MarkupSafe==0.23",
                      "md5hash==0.0.1",
                      "passlib==1.7.1",
                      "pbr==1.10.0",
                      "python-dateutil==2.6.0",
                      "python-editor==1.0.3",
                      "pytz==2016.10",
                      "requests==2.13.0",
                      "six==1.10.0",
                      "SQLAlchemy==1.1.5",
                      "sqlalchemy-migrate==0.10.0",
                      "SQLAlchemy-Utils==0.32.12",
                      "sqlparse==0.2.2",
                      "stevedore==1.20.0",
                      "Tempita==0.5.2",
                      "tzlocal==1.3",
                      "virtualenv==15.1.0",
                      "virtualenv-clone==0.2.6",
                      "virtualenvwrapper==4.7.2",
                      "Werkzeug==0.11.15",
                      "WTForms==2.1"]
)
